// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: version.proto

/*
Package com_sinlov_demo_micro_restful is a generated protocol buffer package.

It is generated from these files:
	version.proto

It has these top-level messages:
	Request
	Response
*/
package com_sinlov_demo_micro_restful

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
	context "context"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for Version service

type VersionService interface {
	Version(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
}

type versionService struct {
	c    client.Client
	name string
}

func NewVersionService(name string, c client.Client) VersionService {
	if c == nil {
		c = client.NewClient()
	}
	if len(name) == 0 {
		name = "com.sinlov.demo.micro.restful"
	}
	return &versionService{
		c:    c,
		name: name,
	}
}

func (c *versionService) Version(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "Version.Version", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Version service

type VersionHandler interface {
	Version(context.Context, *Request, *Response) error
}

func RegisterVersionHandler(s server.Server, hdlr VersionHandler, opts ...server.HandlerOption) error {
	type version interface {
		Version(ctx context.Context, in *Request, out *Response) error
	}
	type Version struct {
		version
	}
	h := &versionHandler{hdlr}
	return s.Handle(s.NewHandler(&Version{h}, opts...))
}

type versionHandler struct {
	VersionHandler
}

func (h *versionHandler) Version(ctx context.Context, in *Request, out *Response) error {
	return h.VersionHandler.Version(ctx, in, out)
}
